config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get '/profile', to: 'pages#profile'
  get '/profile/:exchange', to: 'pages#confirm?', as: 'confirm'
  devise_for :users
  # shortcut for all the routes (show, edit, update, new, etc.)
  resources :items do
    # shortcut for => get "/items/:item_id/comments/new"
    resources :comments, only: [:new, :create]
    resources :exchanges, only: [:new, :create]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :comments, only: [:destroy]
  resources :exchanges, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :item

  validates :content, presence: true
end

app/models/exchange.rb
class Exchange < ApplicationRecord
  belongs_to :item
  belongs_to :user

  validates :date, :location, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many :exchanges, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many_attached :pictures

  # , :maximum => 3

  # Item::CATEGORIES => Call this ANYWHERE in the app
  CATEGORIES = %w(Clothing Furniture Appliances Electronics DIY Garden Travel Other)
  validates :name, :description, :category, presence: true
  validates :category, inclusion: { in: CATEGORIES }
  validates :description, length: { minimum: 10 }

  def time_since_posted
    time_diff = Time.now - created_at
    if (time_diff / 1.minute).round == 1
      return "#{(time_diff / 1.minute).round} minute ago"
    elsif (time_diff / 1.minute).round < 60
      return "#{(time_diff / 1.minute).round} minutes ago"
    elsif (time_diff / 1.hour).round == 1
      return "#{(time_diff / 1.hour).round} hour ago"
    elsif (time_diff / 1.hour).round < 24
      return "#{(time_diff / 1.hour).round} hours ago"
    elsif (time_diff / 1.day).round == 1
      return "#{(time_diff / 1.day).round} day ago"
    else
      return "#{(time_diff / 1.day).round} days ago"
    end
  end

  include PgSearch::Model
   pg_search_scope :search_by_category_and_name,
    against: [ :category, :name ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :items, dependent: :destroy
  has_many :comments, through: :items, dependent: :destroy
  has_many :exchanges, dependent: :destroy
  has_one_attached :photo

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # validates :first_name, :last_name, :location, presence: true
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  def distance_from_item(item)
    distance_in_miles = self.distance_to(item.user).round(1)
    "#{distance_in_miles} miles away"
  end

  def item_distance(item)
    distance_in_miles = self.distance_to(item.user)
    unless distance_in_miles.nil?
      return distance_in_miles.round(1)
    else
      return 10
    end
  end

  def notifications
    notifications = 0
    self.items.each do |item|
      if item.exchanges.last
        if item.exchanges.last.confirmed == false
          notifications += 1
        end
      end
    end
    return notifications
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
    stored_location_for(resource) || items_path
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :location, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:email, :first_name, :last_name, :location, :photo])
  end
end

app/controllers/exchanges_controller.rb
class ExchangesController < ApplicationController
  def new
    @item = Item.find(params[:item_id])
    @exchange = Exchange.new
  end

  def create
    @exchange = Exchange.new(exchange_params)
    @item = Item.find(params[:item_id])
    @exchange.item = @item
    @exchange.user = current_user
    if @exchange.save
      flash[:notice] = "Collection request sent!"
      redirect_to profile_path
    else
      @user = current_user
      render 'items/show'
    end
  end

  def destroy
    @exchange = Exchange.find(params[:id])
    @exchange.destroy
    flash[:notice] = "The collection has been removed!"
    redirect_to profile_path
  end

  private

  def exchange_params
    params.require(:exchange).permit(:location, :date)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i(show edit update destroy)
  before_action :find_user
  skip_before_action :authenticate_user!, only: %i(index show)
  before_action :notification_alert

  @@alert = 0

  def index
    if params[:query].present?
      sql_query = "category ILIKE :query OR name ILIKE :query"
      @items = Item.where.not(user: @user)
      @items = @items.where(sql_query, query: "%#{params[:query]}%")
    else
      @items = Item.where.not(user: @user)
      if params[:sort] == "Newest"
        @items = @items.sort_by { |i| i.created_at }.reverse

      elsif params[:sort] == "Nearest"
       @items = @items.sort_by { |item| @user.item_distance(item) }
      end
    end
  end

  def show
    @exchange = Exchange.new
    if @user
      user_marker = {
        lat: @user.latitude,
        lng: @user.longitude,
        image_url: helpers.asset_url('user_location')
      }
    end
    item_marker = {
      lat: @item.user.latitude,
      lng: @item.user.longitude,
      image_url: helpers.asset_url('item_location')
    }
    @markers = [item_marker, user_marker]
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.user = current_user
    if @item.save
      flash[:notice] = "Thanks! Your item has been added!"
      redirect_to item_path(@item)
    else
      render :new
    end
  end


  def edit
  end

  def update
    @item.update(item_params)
    if @item.save
      flash[:notice] = "Your item has been successfully edited!"
      redirect_to item_path(@item)
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    flash[:notice] = "Your item has been removed!"
    redirect_to items_path
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def find_user
    @user = current_user
  end

  def item_params
    params.require(:item).permit(:name, :description, :category, pictures: [])
  end

  def notification_alert
    @user = current_user
    if @user
      if @user.notifications > @@alert
        flash[:notice] = "You received a request for an item!"
        @@alert += 1
      end
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[home profile]

  def home
    @user = current_user
  end

  def profile
    @user = current_user
    @items = @user.items
    @requests = @user.exchanges
    @planned_collections = []
    @exchanges = []
    @donations = []
    @items.each do |item|
      unless item.exchanges.last.nil?
        if item.exchanges.last.confirmed && item.exchanges.last.date < Time.now
          @donations << item
        elsif item.exchanges.last.confirmed
          @planned_collections << item
          @planned_collections.sort_by! { |item| item.exchanges.last.date }
        elsif !item.exchanges.last.confirmed
          @exchanges << item.exchanges.last
        end
      end
    end

  end

  def confirm?
    exchange = Exchange.find(params[:exchange])
    exchange.confirmed = true
    exchange.save
    flash[:notice] = "Collection confirmed!"
    redirect_to profile_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/edit.html.erb
<div class="container pt-5">
  <div class="row justify-content-center p-3">
    <div class="col-8">
      <div class="add-item">
        <%= simple_form_for @item do |f| %>
          <%= f.input :name %>
          <%= f.input :description %>
          <%= f.input :category, collection: Item::CATEGORIES %>
          <%= f.input :pictures, as: :file, input_html: { multiple: true } %>
          <%= f.submit %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/items/index.html.erb
<div class="container">
  <div class="header py-3">
    <% if @items.empty? %>
      <h1>Nothing matched your search</h1>
    <% else %>
      <h1><%= pluralize(@items.count, 'item') %> available for collection</h1>
    <% end %>
    </div>
    <div class="header py-2 d-flex justify-content-between align-items-center">
    <div class="search-bar">
     <%= form_tag items_path, method: :get ,class: "form-inline" do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Search items"
    %>
    <%= submit_tag "Begin", class: "btn btn-primary btn-sm" %>
    </div>
    <div class="sort-by">
      <%= form_tag items_path, method: :get ,class: "form-inline" do %>
        <%= select_tag "sort", options_for_select(%w(Newest Nearest)) %>
        <%= submit_tag "Sort", class: "btn btn-primary" %>
      <% end %>

    </div>

    </div>
    <div class="cards">
      <% @items.each do |item| %>
      <div class="card-holder">
        <%= link_to item_path(item) do %>
          <div class="card-index">
            <% if item.pictures[1] %>
              <%= cl_image_tag item.pictures[1].key %>
            <% else %>
                <%= image_tag "https://source.unsplash.com/random", alt: "alttext" %>
            <% end %>

            <div class="item-status">
              <% if ((Time.now - item.created_at) / 1.minute).round < 60 %>
                <p class="badge p-2 alert-warning">New!</p>
              <% end %>
            </div>

            <div class="card-index-info">
              <div class="card-index-info-top">
                <h2><%= item.name.capitalize %></h2>
                <h2><%= item.category %></h2>
              </div>
              <div class="card-index-info-bottom">
                <p>Donated <%= item.time_since_posted %> by <%= item.user.first_name.capitalize %></p>
                <p>
                  <% if @user && @user.latitude && item.user.latitude %>
                    <%= @user.distance_from_item(item) %>
                  <% else %>
                    <%= item.user.location %>
                  <% end %>
                </p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <% end %>
    </div>
  <% end %>
  <!-- <div class="container"> -->
    <% if current_user %>
    <div class="item-header">
      <h5>My items</h5>

    </div>
      <div class="cards">
      <% current_user.items.each do |item| %>
        <div class="card-holder">
          <%= link_to item_path(item) do %>
            <div class="card-index">
              <% if item.pictures[1] %>
                <%= cl_image_tag item.pictures[1].key %>
              <% else %>
                  <%= image_tag "https://source.unsplash.com/random", alt: "alttext" %>
              <% end %>
              <div class="card-index-info">
                <div class="card-index-info-top">
                  <h2><%= item.name.capitalize %></h2>
                  <h2><%= item.category %></h2>
                </div>
                <div class="card-index-info-bottom">
                  <p>Donated <%= item.time_since_posted %></p>

                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
    <% end %>
  <!-- </div> -->

app/views/items/new.html.erb
<div class="container pt-5">
  <div class="row justify-content-center p-3">
    <div class="col-8">
      <div class="add-item">
        <%= simple_form_for(@item) do |f| %>
          <%= f.input :name %>
          <%= f.input :description %>
          <%= f.input :category, collection: Item::CATEGORIES %>
          <%= f.input :pictures, as: :file, input_html: { multiple: true } %>
          <%= f.submit %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/items/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 order-1">
      <% if @item.pictures %>
        <%= render 'shared/carousel' %>
      <% end %>
      <div class="item-status">
        <% if @item.exchanges.first %>
          <% if @item.exchanges.first.confirmed %>
            <p class="badge p-2 alert-dark">Item reserved</p>
          <% else %>
            <p class="badge p-2 alert-danger">Pending collection</p>
          <% end %>
        <% else %>
          <p class="badge p-2 alert-success">Item available!</p>
        <% end %>
      </div>
    </div>
    <div class="col-12 col-lg-8 order-2 middle">
      <div class="show-info-upper">
        <h1>
          <%= @item.name.capitalize %>
          <% if @user == @item.user %>
            <%= link_to edit_item_path(@item) do %>
              <i class="fas fa-edit">|</i>
            <% end %>
            <%= link_to item_path(@item), method: :delete do %>
              <i class="fas fa-trash-alt"></i>
            <% end %>
          <% end %>
        </h1>
        <h3><%= @item.category %></h3>
      </div>
      <div class="show-info-lower">
        <div class="show-time-user">
          <p>Donated <%= @item.time_since_posted %> by <%= @item.user.first_name.capitalize %></p>
        </div>
        <div class="item-location">
          <% if @user && @user.latitude && @item.user.latitude %>
            <i class="fas fa-map-marker-alt"></i> <%= @user.distance_from_item(@item) %>
          <% else %>
            <i class="fas fa-map-marker-alt"></i> <%= @item.user.location %>
          <% end %>
        </div>
      </div>
      <div class="show-description">
        <p><%= @item.description.capitalize %></p>
      </div>
    </div>
    <div class="map-container col-12 order-3">
      <div id="map"
           style="width: 100%;
           height: 600px;"
           data-markers="<%= @markers.to_json %>"
           data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
    </div>
    <div class="col-12 col-lg-4 order-2 middle">
      <div class="booking-form">
        <% if @user == @item.user %>
          <p><em>Thanks for donating an item with Reuseful!</em></p>
        <% elsif @user && @item.exchanges.last && @item.exchanges.last.user == @user %>
          <p><em>You have already requested this item! Your request has been sent to <%= @item.user.first_name.capitalize %></em></p>
        <% elsif @user && @item.exchanges.last %>
          <p><em>Another user has already requested this item!</em></p>
        <% elsif @user %>
          <h3>Book a collection</h3>
          <%= simple_form_for [ @item, @exchange ] do |f| %>
            <%= f.input :date, as: :datetime, html5: true %>
            <%= f.input :location %>
            <%= f.submit "Create collection", class: "btn btn-primary submit-button" %>
          <% end %>
        <% else %>
          <p><em><%= link_to "Log in", new_user_session_path %> to book a collection!</em></p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reuseful</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link href="https://fonts.googleapis.com/css?family=Nunito:300,400&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/pages/profile.html.erb
<div class="container">
  <div class="row py-3">
    <div class="col-4">
      <% if user_signed_in? %>
      <div class="profile sticky-top text-center">
        <div class="profile-header p-3">
          <% if @user.photo.attached? %>
            <%= cl_image_tag @user.photo.key, class: "avatar-large" %>
          <% end %>
          <h4 class="pt-4"><%= @user.first_name + " " + @user.last_name %></h4>
        </div>

        <div class="profile-footer p-4">
          <h6><%= @user.location %></h6>
          <h6><%= pluralize @donations.count, "item" %> donated</h6>
           <%= link_to "Edit your profile", edit_user_registration_path, class: "edit-profile" %>
        </div>
      </div>
    </div>

    <div class="col-8">
      <% unless @requests.where(confirmed: true).blank? %>
        <div class="listings">
          <h5>Your upcoming collections</h5>
          <% @requests.each do |request| %>
            <% if request.confirmed %>
              <div class="exchange d-flex align-items-center justify-content-between">
                <h6><%= link_to request.item.name.capitalize, item_path(request.item) %></h6>
                <p><%= request.location.capitalize %></p>
                <p><%= request.date.to_formatted_s(:short)  %></p>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %>

      <% unless @requests.where(confirmed: false).blank? %>
        <div class="listings">
          <h5>Items requested</h5>
          <% @requests.each do |request| %>
            <% if !request.confirmed %>
              <div class="exchange d-flex align-items-center justify-content-between">
                <h6><%= link_to request.item.name.capitalize, item_path(request.item) %></h6>
                <p><%= request.date.to_formatted_s(:short)  %></p>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %>

      <% unless @planned_collections.blank? %>
        <div class="listings">
          <h5>Your upcoming donations</h5>
          <% @planned_collections.each do |request| %>
            <div class="exchange d-flex align-items-center justify-content-between">
              <h6><%= link_to request.name.capitalize, item_path(request) %></h6>
              <p><%= request.exchanges.last.date.to_formatted_s(:short)  %></p>
            </div>
          <% end %>
        </div>
      <% end %>

      <% unless @exchanges.blank? %>
        <div class="listings">
          <h5>My collection requests</h5>
          <% @exchanges.each do |exchange| %>
            <div class="exchange">
              <div class="donations d-flex align-items-center justify-content-between">
                <h6><%= exchange.user.first_name.capitalize %> sent you a request for your <em><%= link_to exchange.item.name, item_path(exchange.item) %></em>.</h6>
                <p><%= exchange.location.capitalize %> - <%= exchange.date.to_formatted_s(:short) %></p>
              </div>
              <div class="to-confirm">
                <%= link_to "Confirm", confirm_path(exchange: exchange), class: "btn btn-outline-success" %>
                <%= link_to "Decline", exchange_path(exchange), method: :delete, class: "btn btn-outline-warning" %>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>

    </div>
  </div>
  <div class="row align-items-center">
    <div class="col-4">
      <% else %>
        <p><em><%= link_to "Log in", new_user_session_path %> to book a collection!</em></p>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_carousel.html.erb
<div id="show-carousel" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <% @item.pictures.each_with_index do |picture, index| %>
      <div class="carousel-item <%= index == 0 ? 'active' : '' %>">
        <div class="carousel-image">
          <%= cl_image_tag picture.key, height: 600 %>
        </div>
      </div>
    <% end %>
  </div>
  <a class="carousel-control-prev" href="#show-carousel" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#show-carousel" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<!-- some cmment -->

app/views/shared/_flashes.html.erb
<!-- Devise alerts -->

<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

<!-- Items controller alerts -->
<% if flash[:notice] %>
  <div class="alert alert-success alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= flash[:notice] %>
  </div>
<% end %>

app/views/shared/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-8">
      <%= simple_form_for @item do |f| %>
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.input :category %>
        <%= f.submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="background-wrap">
  <div class="header-wrapper container pt-1 pb-2">
    <div class="d-flex justify-content-between align-items-center">
      <div class="main-logo">
        <%= link_to "/items", class: "navbar-brand" do %>
          <i class="fas fa-leaf"></i> Reuseful
        <% end %>
      </div>
        <nav>
          <ul class="main-menu">
            <li><%= link_to "Give an item", new_item_path %></li>
            <!-- <li><a href="#section-7">Profile</a></li> -->
            <li><a href="/">About us</a></li>
            <% if user_signed_in? %>
              <li>
                <% if @user.notifications != 0 %>
                  <%= link_to "/profile" do %>
                    <div class="notification">
                      <%= @user.notifications %>
                    </div>
                  <% end %>
                <% end %>
                <% if current_user.photo.attached? %>
                  <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                <% else %>
                  <%= image_tag "https://www.kindpng.com/picc/m/114-1140943_computer-icons-person-login-transparent-silhouette-icon-png.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                <% end %>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                  <%= link_to "Profile", "/profile", class: "dropdown-item" %>
                  <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                </div>
              </li>
            <% else %>
              <%= link_to "Log in", new_user_session_path, class: "btn btn-rounded btn-primary" %>
            <% end %>
          </ul>
        </nav>
      </div>
    </div>
  </header>
</div>